// Code generated by Slice Machine. DO NOT EDIT.

import EmbedBlock from './EmbedBlock';
import GalleryBlock from './GalleryBlock';
import MenuBlock from './MenuBlock';
import ResourceBlock from './ResourceBlock';
import SoundcloudBlock from './SoundcloudBlock';
import TestimonialBlock from './TestimonialBlock';
import TextBlock from './TextBlock';

export {
	EmbedBlock,
	GalleryBlock,
	MenuBlock,
	ResourceBlock,
	SoundcloudBlock,
	TestimonialBlock,
	TextBlock,
};

export const components = {
	embed_block: EmbedBlock,
	gallery: GalleryBlock,
	menu: MenuBlock,
	resource_block: ResourceBlock,
	soundcloud_block: SoundcloudBlock,
	testimonial_block: TestimonialBlock,
	text_block: TextBlock,
};
