// Code generated by Slice Machine. DO NOT EDIT.

import GalleryBlock from './GalleryBlock';
import MenuBlock from './MenuBlock';
import TestimonialBlock from './TestimonialBlock';
import TextBlock from './TextBlock';

export {
	GalleryBlock,
	MenuBlock,
	TestimonialBlock,
	TextBlock,
};

export const components = {
	gallery: GalleryBlock,
	menu: MenuBlock,
	testimonial_block: TestimonialBlock,
	text_block: TextBlock,
};
