// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  embed_block: dynamic(() => import("./EmbedBlock")),
  events_block: dynamic(() => import("./EventsBlock")),
  gallery: dynamic(() => import("./GalleryBlock")),
  menu: dynamic(() => import("./MenuBlock")),
  noteform_block: dynamic(() => import("./NoteformBlock")),
  resource_block: dynamic(() => import("./ResourceBlock")),
  soundcloud_block: dynamic(() => import("./SoundcloudBlock")),
  testimonial_block: dynamic(() => import("./TestimonialBlock")),
  text_block: dynamic(() => import("./TextBlock")),
  wufoo_form: dynamic(() => import("./WufooForm")),
};
